### PR TITLE
Fix category icons

### LINKED ISSUE #261: Policy category icons not rendering properly

### PR DESCRIPTION
**Pull request by egiurleo**
The category icons were not rendering because we had named them based on their database IDs at one point in time, not realizing that those IDs might change. I've changed the titles of the images to reflect the titles of the categories -- I figure if we change the titles of the categories, we'll probably need new images anyway.

### CODE REVIEW

File: components/Scorecard.js [hunk 1]
```diff
@@ -190,6 +190,8 @@ const Category = ({ category, expanded, onClickExpand, stateData }) => {
     stateData.resource_links.filter(
         (l) => l.category_id === category.id && l.active
     ) || [];
+    const categoryImageName = category.title.replace(/\(|\)/g, '').replace(/\s/g, '-').toLowerCase();
```
Comment (egiurleo) [inline components/Scorecard.js:193]: This line takes the category title, strips any parentheses from it, replaces spaces with dashes, and lower cases it.

**Review by sarahgreen — APPROVED** [review]
Nice, seems like a good move to use the policy category names instead of IDs. LGTM!
